
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  bank-backend:
    build:
      context: .
      dockerfile: bank-backend/Dockerfile
    container_name: bank-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - bank-backend/src/login.env
    volumes:
      - ./bank-backend:/app
    environment:
      - REDIS_HOST=redis
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  bank-frontend:
    build:
      context: .
      dockerfile: bank-frontend/Dockerfile
    container_name: bank-frontend
    ports:
      - "3000:80"
    depends_on:
      - bank-backend
    volumes:
      - ./bank-frontend:/usr/src/app
      - /usr/src/app/node_modules